"""Resources that are marked as 'Training and evaluation data'."""

TRAININGDATA = {
    "corpus": [
        "absabank-imm",
        "analogy",
        "dalaj",
        "dalin-then-swaanska-argus-1732-1734",
        "eukalyptus",
        "faq",
        "semeval2020",
        "sic2",
        "suc2",
        "suc3",
        "swediagnostics",
        "superlim",
        "supersim-superlim",
        "sv-treebank",
        "svensk-fraktur-1626-1816",
        "svenska-tidningar-1818-1870",
        "swe-absa-bank",
        "swefracas",
        "sweparaphrase",
        "swewic",
        "swewinogender",
        "swewinograd",
        "syntag",
        "talbanken-stb",
        "talbanken",
    ],
    "lexicon": [
        "coderoomor",
        "hogskoleprovet-ord",
    ],
    "model": [],
}
